import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { ThemeProvider } from "@/components/Theme-context";
export const metadata: Metadata = {
  title: "Ali's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className="transition-colors duration-2000 delay-300 ease-out">
        <ThemeProvider>
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>

  );
}
