import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { ThemeProvider } from "@/components/Theme-context";
export const metadata: Metadata = {
  title: "Ali's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  

  return (
    <html lang="en" className="dark" >
      <body>
        <ThemeProvider >
        <Header />
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
