import type { Metadata } from "next";
import "../globals.css";
import Header from "@/components/Header";
import { ThemeProvider } from "@/components/Theme-context";
import { NextIntlClientProvider } from "next-intl";
import { ReactNode } from "react";
import { notFound } from "next/navigation";

export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "fa" }];
}

export const metadata: Metadata = {
  title: "Ali's Portfolio",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: ReactNode;
  params: Promise<{ locale: string }>;
}) {
  
  const { locale } = await params;
 

  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch {
    notFound();
  }
 

  return (
    <ThemeProvider>
    <html lang={locale} dir={locale === "fa" ? "rtl" : "ltr"} className={locale ==="fa" ? "font-iranyekan" :""}>
      <body className="transition-colors duration-2000 delay-300 ease-out">
          <NextIntlClientProvider locale={locale} messages={messages}>
            <Header />
            {children}
          </NextIntlClientProvider>
      </body>
    </html>
    </ThemeProvider>

  );
}
